### ISSUE TITLE
Math problems in azure-li-machine-constraints

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#63]
ON the latest test image (`v1.0.34`), I encountered:

```
azurehost:~ # systemctl status -l azure-li-machine-constraints
* azure-li-machine-constraints.service - Validation of Azure Li/VLi machine constraints
   Loaded: loaded (/usr/lib/systemd/system/azure-li-machine-constraints.service; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2018-07-19 21:31:08 UTC; 57min ago
 Main PID: 37535 (code=exited, status=1/FAILURE)

Jul 19 21:31:08 linux azure-li-machine-constraints[37535]:     load_entry_point('azure-li-services==1.1.4', 'console_scripts', 'azure-li-machine-constraints')()
Jul 19 21:31:08 linux azure-li-machine-constraints[37535]:   File "/usr/lib/python3.4/site-packages/azure_li_services/units/machine_constraints.py", line 45, in main
Jul 19 21:31:08 linux azure-li-machine-constraints[37535]:     machine_constraints
Jul 19 21:31:08 linux azure-li-machine-constraints[37535]:   File "/usr/lib/python3.4/site-packages/azure_li_services/units/machine_constraints.py", line 75, in check_main_memory_validates_constraint
Jul 19 21:31:08 linux azure-li-machine-constraints[37535]:     min_bytes, binary=True
Jul 19 21:31:08 linux azure-li-machine-constraints[37535]: azure_li_services.exceptions.AzureHostedMachineConstraintException: Main memory: 1.48 TiB is below required minimum: 1.5 TiB
Jul 19 21:31:08 linux systemd[1]: azure-li-machine-constraints.service: Main process exited, code=exited, status=1/FAILURE
Jul 19 21:31:08 linux systemd[1]: Failed to start Validation of Azure Li/VLi machine constraints.
Jul 19 21:31:08 linux systemd[1]: azure-li-machine-constraints.service: Unit entered failed state.
Jul 19 21:31:08 linux systemd[1]: azure-li-machine-constraints.service: Failed with result 'exit-code'.
Warning: azure-li-machine-constraints.service changed on disk. Run 'systemctl daemon-reload' to reload units.
azurehost:~ #
```

The important part: `Main memory: 1.48 TiB is below required minimum: 1.5 TiB`.

Very very close. The BIOS states that I have 1.5TB, but obviously, the O/S thinks ever so slightly differently.

We can compensate for this by reducing what we believe the memory size to be to memory size - 0.05 TB. Or maybe machine constraints should have a "noise cancellation" for differences?

**Comment by schaefi** [comment]
> maybe machine constraints should have a "noise cancellation" for differences

I'm not so much in favor of adding that. The reason with this type of coding is always that it's broken from the beginning on and stays like that. Where would "noise" stop and turn into "issue" which needs reporting. As this could be never answered because there is no true value I vote to stay strict in the code.

Actually you have the possibility to add "noise canceling" as you see fit in the yaml config file. If your BIOS says you have 1.5TB that's nice but probably immaterial, what I think counts is how much memory does the thing running on the machine need to be useful for the customer. If that value cannot be reached we should strictly fail.

The values taken by our code are retrieved from "proc/meminfo" MemTotal: They map into what Linux calls the virtual memory. I can't tell you exactly what happens here but the BIOS shows you the bare hardware given memory bank without an operating system managing it.
There is always a difference.

**Comment by rjschwei** [comment]
I agree with @schaefi . The "fudge factor" should be in the YAML generator and the checking code should be strict.

**Comment by jeffaco** [comment]
Okay, I'll plan on reducing the values in the YAML by some nominal value to make sure that these memory tests pass in constraints testing. Closing issue.
