### ISSUE TITLE
Need to be able to specify GID for group creation

### ISSUE THREAD

**Issue by jeffaco** [SUSE/azure-li-services#90]
Early on, we made the decision to allow SUSE to choose the GID when creating groups.

It turns out that this won't work. We need to know the UID **AND** GID (not name) in order to set up the storage subsystem (it works from UID and GID, not names). So having the SUSE system choose the GID won't work, since we won't be able to set up storage. Storage must be set up in advance to be able to deploy the O/S.

I had asked for GID originally and, as our operations team was looking at what we provided, they pointed out this restriction. I was previously unaware of this (sorry).

This is a bit of a show-stopper for us, as we can't do a complete UCS (HLI) deployment, which is the next step in testing. I can download the existing image to do basic testing (make sure prior issues that were resolved were indeed fixed), but in terms of the next main test pass, we'll need this.

**Comment by schaefi** [comment]
I think this is not much of a problem if we add an optional group_id attribute. It will not change the schema in an incompatible way, thus I'll go for it and add the support

**Comment by rjschwei** [comment]
There should be a check, the gid  !< 1000. 

0-1000 is reserved for system groups and if a group in that range is specified we will most likely end up with a conflict that will cause problems. Also I could bet that SAP creates user ids thus there is another potential conflict. Maybe check with the SAP team

**Comment by schaefi** [comment]
The group is created without the "--system" option. Thus the groupadd command as I call it will not allow the creation of system groups. See ```man groupadd``` for further details

**Comment by schaefi** [comment]
@jeffaco Some additional information from our SAP team

The SAP-Installation-Wizard creates three groups in the scope of HANA

* sapsys -> GID is requested (old SAP default is 79)
* [sid]shm -> GID is requested
* uuid -> GID is generated from the reserved system account pool between 100 -> 499

That having said you need to be careful because the installation wizard requests at least two groups by ID and that leaves potential for conflicts with the gid feature added here. I got the information that a GID in the range of

* >=500

is considered safe. As we allow only non system groups to be created with the feature added here I would say we are safe

That's just for your reference.

Thanks
